services:
  get-putio:
    build:
      context: .
    container_name: get-putio
    env_file:
      - .env
    ports:
      - "8787:8000"
    volumes:
      - ./data/app:/app/data
      - ${MEDIA_BIND_SOURCE:-./data/media}:/media
    restart: unless-stopped
